/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TelemetryRouteRouteImport } from './routes/telemetry/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VectorsIndexRouteImport } from './routes/vectors/index'
import { Route as TelemetryIndexRouteImport } from './routes/telemetry/index'
import { Route as BenchmarksIndexRouteImport } from './routes/benchmarks/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as ApplicationsIndexRouteImport } from './routes/applications/index'
import { Route as VectorsTextRouteImport } from './routes/vectors/text'
import { Route as VectorsImageRouteImport } from './routes/vectors/image'
import { Route as TelemetryTracesRouteImport } from './routes/telemetry/traces'
import { Route as TelemetryMetricsRouteImport } from './routes/telemetry/metrics'
import { Route as TelemetryLogsRouteImport } from './routes/telemetry/logs'
import { Route as AuthUsersRouteImport } from './routes/auth/users'
import { Route as AuthRolesRouteImport } from './routes/auth/roles'
import { Route as AuthOauthRouteImport } from './routes/auth/oauth'
import { Route as ApplicationsAppIdRouteRouteImport } from './routes/applications/$appId/route'
import { Route as ApplicationsAppIdIndexRouteImport } from './routes/applications/$appId/index'
import { Route as ApplicationsAppIdConfigRouteImport } from './routes/applications/$appId/config'
import { Route as ApplicationsAppIdDataDatabaseTableRouteImport } from './routes/applications/$appId/data/$database.$table'

const TelemetryRouteRoute = TelemetryRouteRouteImport.update({
  id: '/telemetry',
  path: '/telemetry',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VectorsIndexRoute = VectorsIndexRouteImport.update({
  id: '/vectors/',
  path: '/vectors/',
  getParentRoute: () => rootRouteImport,
} as any)
const TelemetryIndexRoute = TelemetryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TelemetryRouteRoute,
} as any)
const BenchmarksIndexRoute = BenchmarksIndexRouteImport.update({
  id: '/benchmarks/',
  path: '/benchmarks/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsIndexRoute = ApplicationsIndexRouteImport.update({
  id: '/applications/',
  path: '/applications/',
  getParentRoute: () => rootRouteImport,
} as any)
const VectorsTextRoute = VectorsTextRouteImport.update({
  id: '/vectors/text',
  path: '/vectors/text',
  getParentRoute: () => rootRouteImport,
} as any)
const VectorsImageRoute = VectorsImageRouteImport.update({
  id: '/vectors/image',
  path: '/vectors/image',
  getParentRoute: () => rootRouteImport,
} as any)
const TelemetryTracesRoute = TelemetryTracesRouteImport.update({
  id: '/traces',
  path: '/traces',
  getParentRoute: () => TelemetryRouteRoute,
} as any)
const TelemetryMetricsRoute = TelemetryMetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => TelemetryRouteRoute,
} as any)
const TelemetryLogsRoute = TelemetryLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => TelemetryRouteRoute,
} as any)
const AuthUsersRoute = AuthUsersRouteImport.update({
  id: '/auth/users',
  path: '/auth/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRolesRoute = AuthRolesRouteImport.update({
  id: '/auth/roles',
  path: '/auth/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthOauthRoute = AuthOauthRouteImport.update({
  id: '/auth/oauth',
  path: '/auth/oauth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsAppIdRouteRoute = ApplicationsAppIdRouteRouteImport.update({
  id: '/applications/$appId',
  path: '/applications/$appId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsAppIdIndexRoute = ApplicationsAppIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ApplicationsAppIdRouteRoute,
} as any)
const ApplicationsAppIdConfigRoute = ApplicationsAppIdConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => ApplicationsAppIdRouteRoute,
} as any)
const ApplicationsAppIdDataDatabaseTableRoute =
  ApplicationsAppIdDataDatabaseTableRouteImport.update({
    id: '/data/$database/$table',
    path: '/data/$database/$table',
    getParentRoute: () => ApplicationsAppIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/telemetry': typeof TelemetryRouteRouteWithChildren
  '/applications/$appId': typeof ApplicationsAppIdRouteRouteWithChildren
  '/auth/oauth': typeof AuthOauthRoute
  '/auth/roles': typeof AuthRolesRoute
  '/auth/users': typeof AuthUsersRoute
  '/telemetry/logs': typeof TelemetryLogsRoute
  '/telemetry/metrics': typeof TelemetryMetricsRoute
  '/telemetry/traces': typeof TelemetryTracesRoute
  '/vectors/image': typeof VectorsImageRoute
  '/vectors/text': typeof VectorsTextRoute
  '/applications/': typeof ApplicationsIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/benchmarks/': typeof BenchmarksIndexRoute
  '/telemetry/': typeof TelemetryIndexRoute
  '/vectors/': typeof VectorsIndexRoute
  '/applications/$appId/config': typeof ApplicationsAppIdConfigRoute
  '/applications/$appId/': typeof ApplicationsAppIdIndexRoute
  '/applications/$appId/data/$database/$table': typeof ApplicationsAppIdDataDatabaseTableRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/oauth': typeof AuthOauthRoute
  '/auth/roles': typeof AuthRolesRoute
  '/auth/users': typeof AuthUsersRoute
  '/telemetry/logs': typeof TelemetryLogsRoute
  '/telemetry/metrics': typeof TelemetryMetricsRoute
  '/telemetry/traces': typeof TelemetryTracesRoute
  '/vectors/image': typeof VectorsImageRoute
  '/vectors/text': typeof VectorsTextRoute
  '/applications': typeof ApplicationsIndexRoute
  '/auth': typeof AuthIndexRoute
  '/benchmarks': typeof BenchmarksIndexRoute
  '/telemetry': typeof TelemetryIndexRoute
  '/vectors': typeof VectorsIndexRoute
  '/applications/$appId/config': typeof ApplicationsAppIdConfigRoute
  '/applications/$appId': typeof ApplicationsAppIdIndexRoute
  '/applications/$appId/data/$database/$table': typeof ApplicationsAppIdDataDatabaseTableRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/telemetry': typeof TelemetryRouteRouteWithChildren
  '/applications/$appId': typeof ApplicationsAppIdRouteRouteWithChildren
  '/auth/oauth': typeof AuthOauthRoute
  '/auth/roles': typeof AuthRolesRoute
  '/auth/users': typeof AuthUsersRoute
  '/telemetry/logs': typeof TelemetryLogsRoute
  '/telemetry/metrics': typeof TelemetryMetricsRoute
  '/telemetry/traces': typeof TelemetryTracesRoute
  '/vectors/image': typeof VectorsImageRoute
  '/vectors/text': typeof VectorsTextRoute
  '/applications/': typeof ApplicationsIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/benchmarks/': typeof BenchmarksIndexRoute
  '/telemetry/': typeof TelemetryIndexRoute
  '/vectors/': typeof VectorsIndexRoute
  '/applications/$appId/config': typeof ApplicationsAppIdConfigRoute
  '/applications/$appId/': typeof ApplicationsAppIdIndexRoute
  '/applications/$appId/data/$database/$table': typeof ApplicationsAppIdDataDatabaseTableRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/telemetry'
    | '/applications/$appId'
    | '/auth/oauth'
    | '/auth/roles'
    | '/auth/users'
    | '/telemetry/logs'
    | '/telemetry/metrics'
    | '/telemetry/traces'
    | '/vectors/image'
    | '/vectors/text'
    | '/applications/'
    | '/auth/'
    | '/benchmarks/'
    | '/telemetry/'
    | '/vectors/'
    | '/applications/$appId/config'
    | '/applications/$appId/'
    | '/applications/$appId/data/$database/$table'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/oauth'
    | '/auth/roles'
    | '/auth/users'
    | '/telemetry/logs'
    | '/telemetry/metrics'
    | '/telemetry/traces'
    | '/vectors/image'
    | '/vectors/text'
    | '/applications'
    | '/auth'
    | '/benchmarks'
    | '/telemetry'
    | '/vectors'
    | '/applications/$appId/config'
    | '/applications/$appId'
    | '/applications/$appId/data/$database/$table'
  id:
    | '__root__'
    | '/'
    | '/telemetry'
    | '/applications/$appId'
    | '/auth/oauth'
    | '/auth/roles'
    | '/auth/users'
    | '/telemetry/logs'
    | '/telemetry/metrics'
    | '/telemetry/traces'
    | '/vectors/image'
    | '/vectors/text'
    | '/applications/'
    | '/auth/'
    | '/benchmarks/'
    | '/telemetry/'
    | '/vectors/'
    | '/applications/$appId/config'
    | '/applications/$appId/'
    | '/applications/$appId/data/$database/$table'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TelemetryRouteRoute: typeof TelemetryRouteRouteWithChildren
  ApplicationsAppIdRouteRoute: typeof ApplicationsAppIdRouteRouteWithChildren
  AuthOauthRoute: typeof AuthOauthRoute
  AuthRolesRoute: typeof AuthRolesRoute
  AuthUsersRoute: typeof AuthUsersRoute
  VectorsImageRoute: typeof VectorsImageRoute
  VectorsTextRoute: typeof VectorsTextRoute
  ApplicationsIndexRoute: typeof ApplicationsIndexRoute
  AuthIndexRoute: typeof AuthIndexRoute
  BenchmarksIndexRoute: typeof BenchmarksIndexRoute
  VectorsIndexRoute: typeof VectorsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/telemetry': {
      id: '/telemetry'
      path: '/telemetry'
      fullPath: '/telemetry'
      preLoaderRoute: typeof TelemetryRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vectors/': {
      id: '/vectors/'
      path: '/vectors'
      fullPath: '/vectors/'
      preLoaderRoute: typeof VectorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/telemetry/': {
      id: '/telemetry/'
      path: '/'
      fullPath: '/telemetry/'
      preLoaderRoute: typeof TelemetryIndexRouteImport
      parentRoute: typeof TelemetryRouteRoute
    }
    '/benchmarks/': {
      id: '/benchmarks/'
      path: '/benchmarks'
      fullPath: '/benchmarks/'
      preLoaderRoute: typeof BenchmarksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications/': {
      id: '/applications/'
      path: '/applications'
      fullPath: '/applications/'
      preLoaderRoute: typeof ApplicationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vectors/text': {
      id: '/vectors/text'
      path: '/vectors/text'
      fullPath: '/vectors/text'
      preLoaderRoute: typeof VectorsTextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vectors/image': {
      id: '/vectors/image'
      path: '/vectors/image'
      fullPath: '/vectors/image'
      preLoaderRoute: typeof VectorsImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/telemetry/traces': {
      id: '/telemetry/traces'
      path: '/traces'
      fullPath: '/telemetry/traces'
      preLoaderRoute: typeof TelemetryTracesRouteImport
      parentRoute: typeof TelemetryRouteRoute
    }
    '/telemetry/metrics': {
      id: '/telemetry/metrics'
      path: '/metrics'
      fullPath: '/telemetry/metrics'
      preLoaderRoute: typeof TelemetryMetricsRouteImport
      parentRoute: typeof TelemetryRouteRoute
    }
    '/telemetry/logs': {
      id: '/telemetry/logs'
      path: '/logs'
      fullPath: '/telemetry/logs'
      preLoaderRoute: typeof TelemetryLogsRouteImport
      parentRoute: typeof TelemetryRouteRoute
    }
    '/auth/users': {
      id: '/auth/users'
      path: '/auth/users'
      fullPath: '/auth/users'
      preLoaderRoute: typeof AuthUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/roles': {
      id: '/auth/roles'
      path: '/auth/roles'
      fullPath: '/auth/roles'
      preLoaderRoute: typeof AuthRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/oauth': {
      id: '/auth/oauth'
      path: '/auth/oauth'
      fullPath: '/auth/oauth'
      preLoaderRoute: typeof AuthOauthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications/$appId': {
      id: '/applications/$appId'
      path: '/applications/$appId'
      fullPath: '/applications/$appId'
      preLoaderRoute: typeof ApplicationsAppIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications/$appId/': {
      id: '/applications/$appId/'
      path: '/'
      fullPath: '/applications/$appId/'
      preLoaderRoute: typeof ApplicationsAppIdIndexRouteImport
      parentRoute: typeof ApplicationsAppIdRouteRoute
    }
    '/applications/$appId/config': {
      id: '/applications/$appId/config'
      path: '/config'
      fullPath: '/applications/$appId/config'
      preLoaderRoute: typeof ApplicationsAppIdConfigRouteImport
      parentRoute: typeof ApplicationsAppIdRouteRoute
    }
    '/applications/$appId/data/$database/$table': {
      id: '/applications/$appId/data/$database/$table'
      path: '/data/$database/$table'
      fullPath: '/applications/$appId/data/$database/$table'
      preLoaderRoute: typeof ApplicationsAppIdDataDatabaseTableRouteImport
      parentRoute: typeof ApplicationsAppIdRouteRoute
    }
  }
}

interface TelemetryRouteRouteChildren {
  TelemetryLogsRoute: typeof TelemetryLogsRoute
  TelemetryMetricsRoute: typeof TelemetryMetricsRoute
  TelemetryTracesRoute: typeof TelemetryTracesRoute
  TelemetryIndexRoute: typeof TelemetryIndexRoute
}

const TelemetryRouteRouteChildren: TelemetryRouteRouteChildren = {
  TelemetryLogsRoute: TelemetryLogsRoute,
  TelemetryMetricsRoute: TelemetryMetricsRoute,
  TelemetryTracesRoute: TelemetryTracesRoute,
  TelemetryIndexRoute: TelemetryIndexRoute,
}

const TelemetryRouteRouteWithChildren = TelemetryRouteRoute._addFileChildren(
  TelemetryRouteRouteChildren,
)

interface ApplicationsAppIdRouteRouteChildren {
  ApplicationsAppIdConfigRoute: typeof ApplicationsAppIdConfigRoute
  ApplicationsAppIdIndexRoute: typeof ApplicationsAppIdIndexRoute
  ApplicationsAppIdDataDatabaseTableRoute: typeof ApplicationsAppIdDataDatabaseTableRoute
}

const ApplicationsAppIdRouteRouteChildren: ApplicationsAppIdRouteRouteChildren =
  {
    ApplicationsAppIdConfigRoute: ApplicationsAppIdConfigRoute,
    ApplicationsAppIdIndexRoute: ApplicationsAppIdIndexRoute,
    ApplicationsAppIdDataDatabaseTableRoute:
      ApplicationsAppIdDataDatabaseTableRoute,
  }

const ApplicationsAppIdRouteRouteWithChildren =
  ApplicationsAppIdRouteRoute._addFileChildren(
    ApplicationsAppIdRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TelemetryRouteRoute: TelemetryRouteRouteWithChildren,
  ApplicationsAppIdRouteRoute: ApplicationsAppIdRouteRouteWithChildren,
  AuthOauthRoute: AuthOauthRoute,
  AuthRolesRoute: AuthRolesRoute,
  AuthUsersRoute: AuthUsersRoute,
  VectorsImageRoute: VectorsImageRoute,
  VectorsTextRoute: VectorsTextRoute,
  ApplicationsIndexRoute: ApplicationsIndexRoute,
  AuthIndexRoute: AuthIndexRoute,
  BenchmarksIndexRoute: BenchmarksIndexRoute,
  VectorsIndexRoute: VectorsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
